baseurl = "/"
languageCode = "en-us"
title = "Known Unknowns"
theme = "hugo-kiera-master"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Email"
    url = "mailto:jb@knownunknowns.co.uk"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gzrcm"
[[menu.main]]
    name = "Linkedin"
    url = "https://uk.linkedin.com/in/jacobbaisley"

[params]
    description = "A website built through Hugo and blogdown."
    tagline = "As our circle of knowledge expands, so does the circumference of darkness surrounding it.<br/>-Albert Einstein"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml","python"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


