---
title: What are you Trying to do?
author: JB
date: '2018-10-18'
slug: what-are-you-trying-to-do
categories:
  - Intelligence Analysis
  - Culture
tags: []
---

What are you trying to do? That’s a question I have to ask clients all too often. This is typically necessitated for one of two reasons: the decision-maker assumes I know something I do not that would help clarify the problem, or more likely the requirements have been poorly articulated. Requirements that are critical to actually doing intelligence. Otherwise we all stumble aimlessly in the dark looking for success.

Analysts are a sounding board to help collate the best information possible to help the decision-maker answer a specific question. If we look upwards to the gilded officers of executive management whose dynamism, entrepreneurial spirit and boundless experience set the direction of companies, task sprawling work forces and motivate them to action with idealism would that sound familiar? I didn’t think so. Management get is wrong all the time, we all do, we are only human. Often their failure is more pronounced because of the shear movement in resources they can direct. But the trick when we fail in those positons is falling gracefully in the most informed way possible. One of the biggest stumbling blocks is articulation.

An intelligence requirement typically answers a specify question for which a decision-maker can act, such as: “How many units do we need to sell to break even?” or “Explain why our customers are leaving  our company.” Requirements come in many forms, but the key is teasing out the specific items for which a tangible and factual outcome can be known or assessed. When resolving requirements will also articulate the source of the intelligence and its reliability in weighting its relevance. That is why intelligence lends itself very well to business planning despite coming from a national security/ policy background. 

But if I asked you to define what a mission statement was? What if I added goals and strategy to that? Could you differentiate between them? I know many who couldn’t and you likely do as well. I have seen decision-makers conflate vision and strategy, even to the point where I have heard a company director thank a CEO for their vision because without it they could not have set the goals to make their strategy a reality… Wait a minute. You crafted your entire department around a vision, that was never vetted, to set goals so you could shoe horn in a strategy without knowing if you could even achieve the outcome? The results were tragic by the way, a botched transformation program which demotivated the work force not to mention how much was lost in budgeting. Yikes. But I see this over and over again. People are lauded for their ideas and grand visions but have no realistic or managerial means of achieving that vision. They jump from the beginning to the end and back again. That is not success and it is not adequate.

The failure in the case above stemmed from how resources were allocated to achieve the goals of the vision. Because the goals were not founded in reality, managers couldn’t measure what “success” looked like leading to different opinions of who was achieving results. So when teams  were relying on each other for those measures the friction and tribalism began. Teams withheld information, backlogs formed, staff moral plummeted. Without some objective truth to inform a starting position the CEO’s vision was like a ship adrift in storm, no stars or sextant and a brewing mutiny as people lost confidence in management’s ability to save them.

Had the intelligence unit I was working for been engaged at a corporate level we could have provided that much needed star to sail by. It may not have been 100% accurate, but we could give the business a true North to orient themselves. Instead it came down to the gut instinct and 30 years of experience the CEO had. That’s great, but the industry they worked of 30 years ago had moved it and their personal experience was irrelevant in a brave new world led by data and algorithms. Worse yet, their inability to engage with new technology didn’t inspire confidence in frontline staff who were desperate for innovation, preforming ridiculous manual work-arounds well outside normal hours just to stay afloat. When we suggested documenting intelligence requirements for the company planning board we were told “but if we make goals explicit and we don’t achieve them, it will look worse. Better to keep it vague.”  I left that company soon after.

Often analysts are so eager to impress and deliver a “good” product that we fail to ask or question “What are you trying to do?” And as uncomfortable and silly as you might feel asking it, even to executives, you owe it to yourself, your colleagues and the decision-maker to be the voice of constructive challenge. We discussed this in an earlier post about culture. Yeah, it can be lonely being the person who asks hard questions, but your goal as an analyst is to manage up and protect your decision-maker form false information. As an analyst your skill set is to sort the complexity of what someone else needs to achieve their goals. If you don’t stand up for the principles of analysis and the scientific method than what are you trying to do? 

