---
title: The Forest and the Trees
author: JB
date: '2018-11-02'
slug: the-forest-and-the-trees
categories:
  - Business_Planning
  - Intelligence Analysis
  - Strategy
tags: []
---

I feel like I make a lot of school days’ comparisons, asking readers to harken back to their teenage years when their unbridled dreams stretched to weekend plans and maybe getting a summer job. I don't like to dwell on the image, but when we are young we cannot conceive of long term plans or consequences. To borrow a term from my high history teacher, "you are here to learn how to be adults." So how many of us thought school was boring. When will I use trigonometry? Why do I care about the war of 1812? (Because British North America defeated the US, that's why!) The point being, usually we cannot conceptualize our long-term goals.

I think the world is currently devoid of long term planning skills. What causes that I cannot guess. Maybe it is the prison of time we have created for ourselves. Political parties only see between elections, sports terms only the season ahead of them, even businesses to the end of the financial year. We don't have great role models for long term management. Everyday I see senior managers looking to the end of a quarter and not future proofing their teams to maximize output. Worse yet they spend most of their business process time doing manual admin tasks that machine learning and software can do, abstracting people from what they are good at, being creative and making choices.

There is no simple solution. But it starts will a desire to imagine the business you work for will exist perpetually, even without you (perish the thought). It will have a legacy that lasts beyond our perception of time existing in roughly the same state for decades if they are lucky. Second is to always imagine what the team could look like in the future. Third, what does success look like? If you had everything in the world what would you do with it?

People often want to put management information in front of process. Designing their decisions methods into simple tick boxes. This is something start-ups don't suffer from as much until they get larger. They keep their business journeys small, simple functions of A to B. Management information is secondary to delivering the service. Now that its delivered, how do you do it better, cheaper and then you have process control and management information. Older or public companies often do the opposite, they chase KPI's because they are simple, regardless of the fact they are not comprehensive or accurate measures of their outputs. And in fairness operating a large or public organisation makes measuring output difficult as you typically exist for a public good (subjective) and not a high end quarter revenue (objective).

The take away today is to think bigger, think farther and not settle for counting the numbers on your abacus when there is a shiny 8GB ram, 256 GB SSD ultra-thin laptop sitting next to you. Often our day to day means we cannot see the forest for the trees, but it is always worth it to step back, take a second to question why or how you preform and do better. Does your measure of progress mirror reality? Does a KPI actually give you insight on how to do things better? In the end, not only will you be more productive, but your humanity will increase by staying true to your nature, being creative!
